### ISSUE TITLE
Failed to receive the invite

### ISSUE THREAD

**Issue by iatharva** [Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks#10]
I got the mail as `Run failed: .github/workflows/invitation.yml`  which is saying that `all jobs have failed`

When I checked the workflow I found out that there is no file called `automate_invite` or it might be deleted by someone mistakenly, that's why it's failed.

Do look into the issue.
I think I will have to make a new issue again to join the organization once the issue is resolved.
Looking forward to joining till then.

**Comment by harikanani** [comment]
@iatharva as I can see there's a `automate_invite` job in workflows you can check in `.github/workflows/invitation.yml`

**Comment by iatharva** [comment]
@harikanani take a look at [this](https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks/actions/runs/1252077775)

**Comment by harikanani** [comment]
Yes, I've checked that but it's already one job setup called `automate_invite`

**Comment by harikanani** [comment]
if you would like to fix the issue I can assign it to you

**Comment by iatharva** [comment]
Actually, I thought there was some kind of mistake from my side, so I closed the previous issue and made a new one but I am still getting the email saying the same thing.
So, what do you think I should try?

**Comment by iatharva** [comment]
Actually @harikanani, I would love to fix the issue but I am not sure how to resolve it.
