### ISSUE TITLE
invite me to organization

### ISSUE THREAD

**Issue by aayush89890** [Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks#5]
### Contact Details

ayush8989049912@gmail.com

### Discord Username

aayush89890

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nitesh-thapliyal** [comment]
Thank you for joining our organization and make sure to check out our discord server for updates 😊

**Comment by aayush89890** [comment]
#### Thanks for the warm welcome @Nitesh-thapliyal I will surely complete the mentioned tasks.
